In [27]:
import aocd
import re
from dotenv import load_dotenv

load_dotenv()

lines = aocd.get_data(day=2, year=2023).splitlines()

print(lines[:10])


['Game 1: 2 red, 2 green; 1 red, 1 green, 2 blue; 3 blue, 3 red, 3 green; 1 blue, 3 green, 7 red; 5 red, 3 green, 1 blue', 'Game 2: 5 green, 4 red, 7 blue; 7 red, 4 green, 4 blue; 8 green, 11 blue, 4 red; 2 red, 18 blue, 3 green; 7 red, 15 blue', 'Game 3: 2 green, 4 blue; 2 red, 2 green; 6 red, 1 green; 2 red, 1 green; 2 green; 5 blue, 5 red', 'Game 4: 10 red, 7 green, 10 blue; 8 red, 2 green; 9 green, 6 red, 5 blue; 8 green, 2 blue, 4 red; 5 green, 9 blue; 10 red, 1 green, 9 blue', 'Game 5: 10 blue, 7 green, 2 red; 2 blue, 4 red; 2 green, 9 blue, 8 red', 'Game 6: 3 green, 8 red; 1 blue, 11 red, 2 green; 2 green, 15 red, 8 blue; 13 red, 6 blue, 3 green', 'Game 7: 4 green, 10 red, 7 blue; 6 red, 9 blue, 9 green; 2 red, 1 blue, 6 green', 'Game 8: 1 red, 3 blue, 2 green; 7 green, 2 blue; 10 green, 1 red, 2 blue; 1 red', 'Game 9: 4 red, 3 green, 11 blue; 6 red, 4 green; 15 red, 7 blue, 7 green', 'Game 10: 7 red, 1 blue, 5 green; 11 red, 7 green, 1 blue; 2 green, 4 blue, 13 red']


In [33]:
import numpy as np

# lines = """Game 1: 3 blue, 4 red; 1 red, 2 green, 6 blue; 2 green
# Game 2: 1 blue, 2 green; 3 green, 4 blue, 1 red; 1 green, 1 blue
# Game 3: 8 green, 6 blue, 20 red; 5 blue, 4 red, 13 green; 5 green, 1 red
# Game 4: 1 green, 3 red, 6 blue; 3 green, 6 red; 3 green, 15 blue, 14 red
# Game 5: 6 red, 1 blue, 3 green; 2 blue, 1 red, 2 green""".splitlines()


idxs = np.array([int(ll.split(":")[0].split()[-1]) for ll in lines])

sets = [ll.split(":")[1].split(";") for ll in lines]

# print(sets)

colors  = ["red", "green", "blue"]
def str2tuple(s):
    ## r,g,b
    res = {"red": 0, "green": 0, "blue": 0}

    ss = s.split(",")
    assert len(ss) <= 3

    for nb_c in ss:
        nb, c = nb_c.strip().split()
        nb = int(nb)
        c = c.strip()
        res[c] = nb

    return (res["red"], res["green"], res["blue"])

tuples = [[str2tuple(ss) for ss in s] for s in sets]


maxs = np.array([12,13,14])

max_in_tuples = np.array([np.stack(s).max(axis=0) for s in tuples])

print(max_in_tuples[:10])

idx_mask = (max_in_tuples <= maxs).all(1)
print(idx_mask[:10])

print(idxs[idx_mask])

res = int(idxs[idx_mask].sum())
print(res)


aocd.submit(int(idxs[idx_mask].sum()), day=2, year=2023)
        



current_day is only available in December (EST)


[[ 7  3  3]
 [ 7  8 18]
 [ 6  2  5]
 [10  9 10]
 [ 8  7 10]
 [15  3  8]
 [10  9  9]
 [ 1 10  3]
 [15  7 11]
 [13  7  4]]
[ True False  True  True  True False  True  True False False]
[  1   3   4   5   7   8  12  13  14  16  20  24  25  28  32  35  36  37
  38  41  44  48  49  51  52  55  58  59  60  61  62  63  64  66  67  68
  69  70  72  74  77  79  82  85  86  87  88  93  94  97  98  99 100]
2776


answer a: None
submitting for part a


That's the right answer!  You are one gold star closer to restoring snow operations. [Continue to Part Two]


Gtk-Message: 17:08:50.281: Not loading module "atk-bridge": The functionality is provided by GTK natively. Please try to not load it.


In [36]:
max_in_tuples.prod(1).sum()

np.int64(68638)