In [45]:
import aocd
import re
from dotenv import load_dotenv

load_dotenv()

lines = aocd.get_data(day=3, year=2023).splitlines()

print(lines[:10])


['............677..........................................................................227.....730..35.......318...........92...166.......', '....%..863..#......................36.............956..337%......692..............*744....$..........*......../.....187..-..................', '..346...*.....475.440....903&..996*...404+.395...*..............*.......&253.223.....................453..535......@....265.....290$........', '.........470.*.....+..........................*.........148...40....361...................883.............*....%............649.............', '.............587..........#..........848*.............../.........................................415....445....947............*...509......', '......170..............922..79*660.......87...802...........................669.152...867...........*.........................926....+.53...', '.......-..#319..915................846......../......120...870*874..610.........$....-.......577.....825.....430$.....689.............

In [46]:

import numpy as np

# lines = """467..114..
# ...*......
# ..35..633.
# ......#...
# 617*......
# .....+.58.
# ..592.....
# ......755.
# ...$.*....
# .664.598..""".splitlines()

arr = np.array([[c for c in line] for line in lines])


lines

['............677..........................................................................227.....730..35.......318...........92...166.......',
 '....%..863..#......................36.............956..337%......692..............*744....$..........*......../.....187..-..................',
 '..346...*.....475.440....903&..996*...404+.395...*..............*.......&253.223.....................453..535......@....265.....290$........',
 '.........470.*.....+..........................*.........148...40....361...................883.............*....%............649.............',
 '.............587..........#..........848*.............../.........................................415....445....947............*...509......',
 '......170..............922..79*660.......87...802...........................669.152...867...........*.........................926....+.53...',
 '.......-..#319..915................846......../......120...870*874..610.........$....-.......577.....825.....430$.....689.......

In [50]:
in_numbers = np.vectorize(lambda x: x in numbers)
is_symbol = np.vectorize(lambda x: x not in white_list)

mask = np.zeros_like(arr, dtype=bool)

mask[:-1, :] += in_numbers(arr[:-1, :]) & is_symbol(arr[1:, :])
mask[1:, :] += in_numbers(arr[1:, :]) & is_symbol(arr[:-1, :])
mask[:, :-1] += in_numbers(arr[:, :-1]) & is_symbol(arr[:, 1:])
mask[:, 1:] += in_numbers(arr[:, 1:]) & is_symbol(arr[:, :-1])
mask[:-1, :-1] += in_numbers(arr[:-1, :-1]) & is_symbol(arr[1:, 1:])
mask[1:, 1:] += in_numbers(arr[1:, 1:]) & is_symbol(arr[:-1, :-1])
mask[1:, :-1] += in_numbers(arr[1:, :-1]) & is_symbol(arr[:-1, 1:])
mask[:-1, 1:] += in_numbers(arr[:-1, 1:]) & is_symbol(arr[1:, :-1])

print(mask.astype(int))
print((in_numbers(arr[:-1, 1:]) & is_symbol(arr[1:, :-1]).astype(int)))

s = 0
for ll, la in zip(lines, mask.astype(int)):
    buf, valid = "", False
    for lll, aaa in zip(ll, la):
        if aaa:
            valid = True    
        if lll.isdigit():
            buf += lll
        else:
            if valid:
                s += int(buf)
                print(buf)
            buf, valid = "", False

    if valid:
        s += int(buf)
        print(buf)
    buf, valid = "", False
        
print(s)
        



[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 0 0]]
677
227
35
318
863
36
956
337
692
744
187
346
475
440
903
996
404
395
253
453
535
265
290
470
148
40
649
587
848
415
445
947
509
170
922
79
660
87
802
152
867
926
319
846
870
874
610
825
430
689
700
693
734
59
247
444
768
569
430
565
82
525
794
171
160
39
25
560
56
70
397
297
422
338
481
220
116
194
529
381
892
856
324
922
60
288
810
747
876
180
41
456
48
110
199
824
471
261
317
1
316
368
365
212
292
70
616
596
699
978
259
309
660
90
634
631
987
2
285
836
13
8
264
945
323
514
634
816
670
648
343
221
157
319
659
238
113
187
863
937
471
274
244
908
610
670
182
618
865
678
85
948
334
21
853
491
524
494
794
401
327
270
164
142
738
579
823
596
263
797
916
632
618
335
996
504
853
646
872
805
788
985
440
310
826
54
104
238
787
79
449
674
204
808
949
396
664

In [49]:
(mask.astype(int))[-3:, -5:]

array([[0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0],
       [1, 1, 0, 0, 0]])

In [51]:
s

498559

In [52]:
aocd.submit(s, day=3, year=2023)

current_day is only available in December (EST)
answer a: None
submitting for part a


That's the right answer!  You are one gold star closer to restoring snow operations. [Continue to Part Two]


Gtk-Message: 09:10:58.283: Not loading module "atk-bridge": The functionality is provided by GTK natively. Please try to not load it.
