In [80]:
import aocd
import re
from dotenv import load_dotenv
import numpy as np

load_dotenv()

lines = aocd.get_data(day=2, year=2024).splitlines()




print(lines[:10])


['9 12 14 16 17 18 15', '86 88 91 94 95 95', '15 18 20 21 23 25 28 32', '70 72 74 77 78 83', '57 60 62 64 63 64 65', '44 45 44 47 46', '33 35 32 33 36 36', '83 86 88 89 87 88 90 94', '56 59 62 65 68 65 68 75', '36 39 40 40 43']


In [9]:
[list(map(int, l.split())) for l in lines]

[[9, 12, 14, 16, 17, 18, 15],
 [86, 88, 91, 94, 95, 95],
 [15, 18, 20, 21, 23, 25, 28, 32],
 [70, 72, 74, 77, 78, 83],
 [57, 60, 62, 64, 63, 64, 65],
 [44, 45, 44, 47, 46],
 [33, 35, 32, 33, 36, 36],
 [83, 86, 88, 89, 87, 88, 90, 94],
 [56, 59, 62, 65, 68, 65, 68, 75],
 [36, 39, 40, 40, 43],
 [87, 90, 93, 95, 95, 97, 94],
 [90, 91, 92, 92, 95, 95],
 [11, 14, 14, 15, 16, 19, 23],
 [35, 37, 39, 39, 44],
 [59, 61, 63, 67, 68, 69],
 [86, 87, 91, 92, 91],
 [33, 36, 38, 39, 43, 44, 47, 47],
 [82, 84, 86, 89, 93, 94, 98],
 [4, 5, 7, 10, 13, 17, 24],
 [51, 54, 60, 63, 64, 67, 68],
 [38, 40, 43, 45, 51, 54, 56, 53],
 [8, 9, 10, 15, 16, 17, 17],
 [24, 26, 33, 34, 38],
 [61, 62, 64, 66, 68, 74, 80],
 [44, 43, 46, 48, 49, 50, 51, 53],
 [5, 2, 5, 8, 6],
 [12, 11, 14, 16, 17, 18, 18],
 [3, 1, 3, 4, 7, 9, 13],
 [60, 58, 59, 62, 63, 70],
 [45, 44, 41, 42, 43, 44, 46],
 [12, 11, 13, 12, 15, 13],
 [56, 53, 50, 52, 53, 53],
 [70, 69, 72, 69, 70, 71, 72, 76],
 [53, 51, 54, 57, 55, 58, 64],
 [26, 24, 26, 2

In [77]:
lines = """7 6 4 2 1
1 2 7 8 9
9 7 6 2 1
1 3 2 4 5
8 6 4 4 1
1 3 6 7 9""".splitlines()


In [ ]:
input =[np.array(list(map(int, l.split()))) for l in lines]


for i in input:
    try:
        i[0:] < i[:-1]
    except:
        print(i)
        break

increasing = np.array([np.all(i[:-1] < i[1:]) for i in input])
decreasing = np.array([np.all(i[:-1] > i[1:]) for i in input])

first = increasing | decreasing

diff = np.array([np.max(np.abs(np.diff(i))) for i in input])

second = (diff >= 1) & (diff <= 3)

s = int(np.sum(first & second))

print(s)
# aocd.submit(s)


[ 9 12 14 16 17 18 15]
510


In [150]:
from tqdm import tqdm


def ok_diff_tol(i):
    d = np.max(np.abs(np.diff(i)))
    if (d >= 1 and d <= 3):
        return True

    d = np.max(np.abs(np.diff(i[1:])))
    if (d >= 1 and d <= 3):
        return True

    d = np.max(np.abs(np.diff(i[:-1])))
    if (d >= 1 and d <= 3):
        return True

    return False

def ok_diff(i):
    d = np.max(np.abs(np.diff(i)))
    if (d >= 1 and d <= 3):
        return True


def increasing_tol(i):
    joker = True

    if i[0] < i[1]:
        prev = i[0]
        first = 1
    else:
        prev = i[1]
        first = 2
    
    r = [int(prev)]
    
    for j in i[first:]:
        if j > prev:
            prev = j
            r.append(int(j))
        else:
            if joker:
                joker = False
                continue 
            else:
                return i


    if len(r) != len(i)-1:
        return i



    return np.array(r)   
       

def decreasing_tol(i):
    joker = True

    if i[0] > i[1]:
        prev = i[0]
        first = 1
    else:
        prev = i[1]
        first = 2

    r = [int(prev)]

    for j in i[first:]:
        if j < prev:
            prev = j
            r.append(int(j))
        else:
            if joker:
                joker = False
                continue 
            else:
                return i

    if len(r) != len(i)-1:
        return i

    return np.array(r)
    
def increasing(i):
    return np.all(i[:-1] < i[1:])

def decreasing(i):
    return np.all(i[:-1] > i[1:])


def test(i):
    i = np.array(i)
    return (increasing(i) or decreasing(i)) and ok_diff(i)


s,n  = 0, 0
for i in input:
    # print("n", end="")
    found = False
    if test(i):
        s+=1
        found = True
        continue

    il = i.tolist()
    
    if found:
        continue

    for j in range(len(i)):
        inp = il
        sub = inp[:j] + inp[j+1:]
        assert len(sub) == len(il)-1

        if test(sub) and not found:
            s+= 1
            found = True
            print(j, sub)
            break
            # print("ok")

    if found:
        print(i, j, s)

    # if increasing(i) and ok_diff_tol(i):
    #     s+= 1
    #     continue


    # j = increasing_tol(i)

    # if increasing(j) and ok_diff(j):
    #     s+= 1
    #     print(i, j)
    #     continue 

    # if decreasing(i) and ok_diff_tol(i):
    #     s+=1
    #     continue

    # j = decreasing_tol(i)
    # if decreasing(j) and ok_diff(j):
    #     s+=1
    #     continue


print(s)

    
aocd.submit(s)







answer a: 510
submitting for part b (part a is already completed)


6 [9, 12, 14, 16, 17, 18]
[ 9 12 14 16 17 18 15] 6 1
4 [86, 88, 91, 94, 95]
[86 88 91 94 95 95] 4 2
7 [15, 18, 20, 21, 23, 25, 28]
[15 18 20 21 23 25 28 32] 7 3
5 [70, 72, 74, 77, 78]
[70 72 74 77 78 83] 5 4
3 [57, 60, 62, 63, 64, 65]
[57 60 62 64 63 64 65] 3 5
2 [36, 39, 40, 43]
[36 39 40 40 43] 2 6
0 [43, 46, 48, 49, 50, 51, 53]
[44 43 46 48 49 50 51 53] 0 7
1 [65, 66, 67, 70, 72, 75]
[65 62 66 67 70 72 75] 1 8
0 [87, 90, 92, 94]
[87 87 90 92 94] 0 9
0 [11, 14, 15, 17, 18]
[ 7 11 14 15 17 18] 0 10
0 [34, 36, 38, 40, 42, 43, 45]
[28 34 36 38 40 42 43 45] 0 11
1 [87, 90, 93, 94]
[87 92 90 93 94] 1 12
5 [84, 81, 78, 75, 73]
[84 81 78 75 73 76] 5 13
4 [13, 10, 8, 7, 4]
[13 10  8  7  4  4] 4 14
5 [12, 11, 10, 9, 7]
[12 11 10  9  7  3] 5 15
4 [99, 97, 94, 93]
[99 97 94 93 86] 4 16
1 [36, 34, 31, 30, 28]
[36 34 34 31 30 28] 1 17
0 [71, 69, 66, 63]
[69 71 69 66 63] 0 18
1 [37, 34, 31, 29]
[37 38 34 31 29] 1 19
0 [51, 50, 47, 46, 45, 42, 39]
[51 51 50 47 46 45 42 39] 0 20
0 [92, 90, 87, 84]
[

Gtk-Message: 08:51:33.670: Not loading module "atk-bridge": The functionality is provided by GTK natively. Please try to not load it.


In [ ]:

def decreasing_tol_right(i):
    joker = True

    if i[0] > i[1]:
        p1 = i[0]
        first = 1
    else:
        p1 = i[1]
        first = 2

    r = [int(p1)]

    p2 = None
    for j in i[first:]:
        if j < p1:
            p1 = j
            p2 = p1
            r.append(int(j))
        else:



            if joker:
                joker = False
                continue 
            else:
                return i

    if len(r) != len(i)-1:
        return i

    return np.array(r)



decreasing_tol([20, 17, 15,  8, 12])

array([20, 17, 15,  8])

In [27]:
from collections import Counter

counters = [Counter(np.abs(np.diff(i)).tolist()) for i in input]

diffs = [np.abs(np.diff(i)) for i in input]

def max_count(i, c):
    m = max(i)
    if c[m] == 1:
        print(i, c)
        return max([n for n in i if n != m])
    return m
    
diff = np.array([max_count(i, c) for i, c in zip(diffs, counters)])

second = (diff >= 1) & (diff <= 3)

s = int(np.sum(first & second))

s

aocd.submit(s)

answer a: 510
submitting for part b (part a is already completed)


[3 2 1 2 2 3 4] Counter({2: 3, 3: 2, 1: 1, 4: 1})
[2 2 3 1 5] Counter({2: 2, 3: 1, 1: 1, 5: 1})
[3 2 2 1 1 1] Counter({1: 3, 2: 2, 3: 1})
[1 1 3 1] Counter({1: 3, 3: 1})
[3 2 1 2 1 2 4] Counter({2: 3, 1: 2, 3: 1, 4: 1})
[3 3 3 3 3 3 7] Counter({3: 6, 7: 1})
[1 1 0 3 0] Counter({1: 2, 0: 2, 3: 1})
[3 0 1 1 3 4] Counter({3: 2, 1: 2, 0: 1, 4: 1})
[2 2 0 5] Counter({2: 2, 0: 1, 5: 1})
[2 2 4 1 1] Counter({2: 2, 1: 2, 4: 1})
[1 4 1 1] Counter({1: 3, 4: 1})
[3 2 1 4 1 3 0] Counter({3: 2, 1: 2, 2: 1, 4: 1, 0: 1})
[1 2 3 3 4 7] Counter({3: 2, 1: 1, 2: 1, 4: 1, 7: 1})
[3 6 3 1 3 1] Counter({3: 3, 1: 2, 6: 1})
[2 3 2 6 3 2 3] Counter({2: 3, 3: 3, 6: 1})
[1 1 5 1 1 0] Counter({1: 4, 5: 1, 0: 1})
[2 7 1 4] Counter({2: 1, 7: 1, 1: 1, 4: 1})
[1 3 2 1 1 1 2] Counter({1: 4, 2: 2, 3: 1})
[1 3 2 1 1 0] Counter({1: 3, 3: 1, 2: 1, 0: 1})
[2 2 1 3 2 4] Counter({2: 3, 1: 1, 3: 1, 4: 1})
[2 1 3 1 7] Counter({1: 2, 2: 1, 3: 1, 7: 1})
[1 3 1 1 1 2] Counter({1: 4, 3: 1, 2: 1})
[1 2 1 3 2] Counter({1: 2, 2: 2, 3

In [46]:

import numpy as np

# lines = """467..114..
# ...*......
# ..35..633.
# ......#...
# 617*......
# .....+.58.
# ..592.....
# ......755.
# ...$.*....
# .664.598..""".splitlines()

arr = np.array([[c for c in line] for line in lines])


lines

['............677..........................................................................227.....730..35.......318...........92...166.......',
 '....%..863..#......................36.............956..337%......692..............*744....$..........*......../.....187..-..................',
 '..346...*.....475.440....903&..996*...404+.395...*..............*.......&253.223.....................453..535......@....265.....290$........',
 '.........470.*.....+..........................*.........148...40....361...................883.............*....%............649.............',
 '.............587..........#..........848*.............../.........................................415....445....947............*...509......',
 '......170..............922..79*660.......87...802...........................669.152...867...........*.........................926....+.53...',
 '.......-..#319..915................846......../......120...870*874..610.........$....-.......577.....825.....430$.....689.......

In [50]:
in_numbers = np.vectorize(lambda x: x in numbers)
is_symbol = np.vectorize(lambda x: x not in white_list)

mask = np.zeros_like(arr, dtype=bool)

mask[:-1, :] += in_numbers(arr[:-1, :]) & is_symbol(arr[1:, :])
mask[1:, :] += in_numbers(arr[1:, :]) & is_symbol(arr[:-1, :])
mask[:, :-1] += in_numbers(arr[:, :-1]) & is_symbol(arr[:, 1:])
mask[:, 1:] += in_numbers(arr[:, 1:]) & is_symbol(arr[:, :-1])
mask[:-1, :-1] += in_numbers(arr[:-1, :-1]) & is_symbol(arr[1:, 1:])
mask[1:, 1:] += in_numbers(arr[1:, 1:]) & is_symbol(arr[:-1, :-1])
mask[1:, :-1] += in_numbers(arr[1:, :-1]) & is_symbol(arr[:-1, 1:])
mask[:-1, 1:] += in_numbers(arr[:-1, 1:]) & is_symbol(arr[1:, :-1])

print(mask.astype(int))
print((in_numbers(arr[:-1, 1:]) & is_symbol(arr[1:, :-1]).astype(int)))

s = 0
for ll, la in zip(lines, mask.astype(int)):
    buf, valid = "", False
    for lll, aaa in zip(ll, la):
        if aaa:
            valid = True    
        if lll.isdigit():
            buf += lll
        else:
            if valid:
                s += int(buf)
                print(buf)
            buf, valid = "", False

    if valid:
        s += int(buf)
        print(buf)
    buf, valid = "", False
        
print(s)
        



[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 0 0]]
677
227
35
318
863
36
956
337
692
744
187
346
475
440
903
996
404
395
253
453
535
265
290
470
148
40
649
587
848
415
445
947
509
170
922
79
660
87
802
152
867
926
319
846
870
874
610
825
430
689
700
693
734
59
247
444
768
569
430
565
82
525
794
171
160
39
25
560
56
70
397
297
422
338
481
220
116
194
529
381
892
856
324
922
60
288
810
747
876
180
41
456
48
110
199
824
471
261
317
1
316
368
365
212
292
70
616
596
699
978
259
309
660
90
634
631
987
2
285
836
13
8
264
945
323
514
634
816
670
648
343
221
157
319
659
238
113
187
863
937
471
274
244
908
610
670
182
618
865
678
85
948
334
21
853
491
524
494
794
401
327
270
164
142
738
579
823
596
263
797
916
632
618
335
996
504
853
646
872
805
788
985
440
310
826
54
104
238
787
79
449
674
204
808
949
396
664

In [49]:
(mask.astype(int))[-3:, -5:]

array([[0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0],
       [1, 1, 0, 0, 0]])

In [51]:
s

498559

In [52]:
aocd.submit(s, day=3, year=2023)

current_day is only available in December (EST)
answer a: None
submitting for part a


That's the right answer!  You are one gold star closer to restoring snow operations. [Continue to Part Two]


Gtk-Message: 09:10:58.283: Not loading module "atk-bridge": The functionality is provided by GTK natively. Please try to not load it.


In [2]:
from aocd import models

p = models.Puzzle(year=2024, day=2)

p.easter_eggs

[<span title="I need to get one of these!">Problem Dampener</span>]