In [51]:
import aocd
import re
from dotenv import load_dotenv
import numpy as np

load_dotenv()

text = aocd.get_data(day=4, year=2024)
lines = text.splitlines()

example = """MMMSXXMASM
MSAMXMSMSA
AMXSXMAAMM
MSAMASMSMX
XMASAMXAMM
XXAMMXXAMA
SMSMSASXSS
SAXAMASAAA
MAMMMXMMMM
MXMXAXMASX
""".splitlines()




In [48]:
lines = example

In [23]:
arr = np.array([[c for c in line] for line in lines])

def iterrows(arr):
    for i in range(arr.shape[0]):
        yield arr[i]

def itercols(arr):
    for i in range(arr.shape[1]):
        yield arr[:, i]

def iterdiag(arr):
    for i in range(-arr.shape[0], arr.shape[1]):
        yield arr.diagonal(i)
    for i in range(-arr.shape[1], arr.shape[0]):
        yield np.flipud(arr).diagonal(i)

def iterall(arr):
    yield from iterrows(arr)
    yield from itercols(arr)
    yield from iterdiag(arr)


s = 0
for i in iterall(arr):
    # print("".join(i))
    l1 = len(re.findall("XMAS", "".join(i)))
    l2 = len(re.findall("SAMX", "".join(i)))
    s += l1 + l2

print(s)
    






2662


In [24]:
aocd.submit(s, day=4, year=2024)

answer a: None
submitting for part a


That's the right answer!  You are one gold star closer to finding the Chief Historian. [Continue to Part Two]


Gtk-Message: 08:17:41.036: Not loading module "atk-bridge": The functionality is provided by GTK natively. Please try to not load it.


In [25]:
import torch

In [ ]:
torch.tensor(arr)

TypeError: can't convert np.ndarray of type numpy.str_. The only supported types are: float64, float32, float16, complex64, complex128, int64, int32, int16, int8, uint64, uint32, uint16, uint8, and bool.

In [52]:
t = torch.tensor([[ord(c) for c in line] for line in lines])

t = t[None, None, :, :] 

patches = t.unfold(2, 3, 1).unfold(3, 3, 1)

patches = patches.contiguous().view(-1, 3, 3)

patches[:, 0, 1] = 0
patches[:, 1, 0] = 0
patches[:, 1, 2] = 0
patches[:, 2, 1] = 0


patterns = []
for x1 in ["MAS", "SAM"]:
    for x2 in ["MAS", "SAM"]:
        a = np.diag([ord(c) for c in x1]) + np.fliplr(np.diag([ord(c) for c in x2]))
        a[1,1] = ord("A")
        print(a)
        patterns.append(a)


s = 0
for p in patterns:
    match = (patches == p).all(dim=(1,2)).bool()


    print(match.sum())
    s += match.sum()

print(s.item())   






[[77  0 77]
 [ 0 65  0]
 [83  0 83]]
[[77  0 83]
 [ 0 65  0]
 [77  0 83]]
[[83  0 77]
 [ 0 65  0]
 [83  0 77]]
[[83  0 83]
 [ 0 65  0]
 [77  0 77]]
tensor(452)
tensor(490)
tensor(521)
tensor(571)
2034


In [53]:
aocd.submit(s.item(), day=4, year=2024)

answer a: 2662
submitting for part b (part a is already completed)


That's the right answer!  You are one gold star closer to finding the Chief Historian.You have completed Day 4! You can [Shareon
  Bluesky
Twitter
Mastodon] this victory or [Return to Your Advent Calendar].


Gtk-Message: 08:30:54.552: Not loading module "atk-bridge": The functionality is provided by GTK natively. Please try to not load it.
