In [13]:
import aocd
import re
from dotenv import load_dotenv
import numpy as np

load_dotenv()

text = aocd.get_data(day=5, year=2024)
lines = text.splitlines()

example = """47|53
97|13
97|61
97|47
75|29
61|13
75|53
29|13
97|29
53|29
61|53
97|53
61|29
47|13
75|47
97|75
47|61
75|61
47|29
75|13
53|13

75,47,61,53,29
97,61,53,29,13
75,29,13
75,97,47,61,53
61,13,29
97,13,75,29,47""".splitlines()




In [2]:
lines = example

In [17]:
orders = [tuple(map(int,l.split("|"))) for l in lines if "|" in l]
numbers = [list(map(int,l.split(","))) for l in lines if "," in l]


def valid(n, orders):
    for o in orders:
        o1,o2 = o
        if not (o1 in n and o2 in n):
            continue

        if n.index(o1) > n.index(o2):
            return False

    return True

s = 0
for n in numbers:
    if valid(n, orders):
        h = len(n)//2
        s+= n[h]

print(s)

# aocd.submit(s)

4578


In [20]:
incorrects = []

numbers = [list(map(int,l.split(","))) for l in lines if "," in l]


def first_incorrect(n, orders):
    for o in orders:
        o1,o2 = o
        if not (o1 in n and o2 in n):
            continue

        if n.index(o1) > n.index(o2):
            return o1, o2



for n in numbers:
    if not valid(n, orders):
        incorrects.append(n)


def sort_incorrects(i, orders):
    o = first_incorrect(i, orders)
    # if o is None:
    #     return i

    k = 0
    while o is not None or k < 1000:
        k += 1


        o = first_incorrect(i, orders)
        if o is None:
            return i
        
        o1, o2 = o
        i1,i2 = i.index(o1), i.index(o2)
        i[i1] = o2
        i[i2] = o1




incorrects = [sort_incorrects(i, orders) for i in incorrects]    

s = 0
for i in incorrects:
    h = len(i)//2
    s += i[h]

print(s)






aocd.submit(s)




answer a: 4578
submitting for part b (part a is already completed)


6179
That's the right answer!  You are one gold star closer to finding the Chief Historian.You have completed Day 5! You can [Shareon
  Bluesky
Twitter
Mastodon] this victory or [Return to Your Advent Calendar].


Gtk-Message: 08:25:49.698: Not loading module "atk-bridge": The functionality is provided by GTK natively. Please try to not load it.


In [24]:
aocd.submit(s, day=4, year=2024)

answer a: None
submitting for part a


That's the right answer!  You are one gold star closer to finding the Chief Historian. [Continue to Part Two]


Gtk-Message: 08:17:41.036: Not loading module "atk-bridge": The functionality is provided by GTK natively. Please try to not load it.


In [25]:
import torch

In [ ]:
torch.tensor(arr)

TypeError: can't convert np.ndarray of type numpy.str_. The only supported types are: float64, float32, float16, complex64, complex128, int64, int32, int16, int8, uint64, uint32, uint16, uint8, and bool.

In [52]:
t = torch.tensor([[ord(c) for c in line] for line in lines])

t = t[None, None, :, :] 

patches = t.unfold(2, 3, 1).unfold(3, 3, 1)

patches = patches.contiguous().view(-1, 3, 3)

patches[:, 0, 1] = 0
patches[:, 1, 0] = 0
patches[:, 1, 2] = 0
patches[:, 2, 1] = 0


patterns = []
for x1 in ["MAS", "SAM"]:
    for x2 in ["MAS", "SAM"]:
        a = np.diag([ord(c) for c in x1]) + np.fliplr(np.diag([ord(c) for c in x2]))
        a[1,1] = ord("A")
        print(a)
        patterns.append(a)


s = 0
for p in patterns:
    match = (patches == p).all(dim=(1,2)).bool()


    print(match.sum())
    s += match.sum()

print(s.item())   






[[77  0 77]
 [ 0 65  0]
 [83  0 83]]
[[77  0 83]
 [ 0 65  0]
 [77  0 83]]
[[83  0 77]
 [ 0 65  0]
 [83  0 77]]
[[83  0 83]
 [ 0 65  0]
 [77  0 77]]
tensor(452)
tensor(490)
tensor(521)
tensor(571)
2034


In [53]:
aocd.submit(s.item(), day=4, year=2024)

answer a: 2662
submitting for part b (part a is already completed)


That's the right answer!  You are one gold star closer to finding the Chief Historian.You have completed Day 4! You can [Shareon
  Bluesky
Twitter
Mastodon] this victory or [Return to Your Advent Calendar].


Gtk-Message: 08:30:54.552: Not loading module "atk-bridge": The functionality is provided by GTK natively. Please try to not load it.


In [21]:
from aocd import models

p = models.Puzzle(year=2024, day=5)

p.easter_eggs

[<span title="Specifically, the surely-stationary stationery stacks.">stationery</span>]